"""Create minimally normalized text and deterministic leakage-safe split manifests."""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

import pandas as pd

from src.data.split import SplitConfig, build_leakage_groups, grouped_multitarget_split, leakage_check
from src.features.text import NormalizationConfig, normalize_text

LOGGER = logging.getLogger("brandpulse.data.prepare")


def _distribution(frame: pd.DataFrame) -> dict[str, object]:
    result: dict[str, object] = {"rows": int(len(frame)), "groups": int(frame["leakage_group"].nunique())}
    for target in ("category", "sentiment", "priority"):
        result[target] = {
            str(label): int(count) for label, count in frame[target].value_counts().to_dict().items()
        }
    return result


def _report_markdown(report: dict[str, object]) -> str:
    lines = [
        "# Preprocessing and Split Report",
        "",
        "Generated by `python -m src.data.prepare`. Rules are fixed and do not learn from validation or test text.",
        "",
        "## Text preprocessing",
        "",
        "- Primary input: `text_raw`; supplied cleaned text is not used as transformer input.",
        "- Applied NFC Unicode normalization, invisible/control-character removal, and whitespace normalization.",
        "- Replaced detected URLs, emails, Bangladeshi mobile numbers, and explicit order/account/transaction identifiers with typed placeholders.",
        "- Preserved Bangla/English negation, punctuation, emoji, and letter case.",
        "- Preserved every prior text representation beside `text_normalized`.",
        "",
        "## Leakage grouping",
        "",
        f"Records: **{report['rows']}**; connected leakage groups: **{report['groups']}**; largest group: **{report['largest_group']}**.",
        "",
        "A connected component joins any comments sharing an exact source URL or a formatting-normalized text signature. Therefore transitive duplicates also stay together.",
        "",
        "## Split sizes",
        "",
        "| Split | Rows | Groups | Percentage |",
        "|---|---:|---:|---:|",
    ]
    splits = report["splits"]
    assert isinstance(splits, dict)
    for name in ("train", "validation", "test"):
        details = splits[name]
        assert isinstance(details, dict)
        lines.append(
            f"| {name} | {details['rows']} | {details['groups']} | {details['percentage']}% |"
        )
    checks = report["leakage_checks"]
    assert isinstance(checks, dict)
    lines.extend(
        [
            "",
            "## Leakage checks",
            "",
            f"- Leakage group overlap: **{checks['leakage_group_overlap_count']}**",
            f"- Source URL overlap: **{checks['source_url_overlap_count']}**",
            f"- Normalized text overlap: **{checks['normalized_text_overlap_count']}**",
            f"- Overall status: **{'PASS' if checks['passed'] else 'FAIL'}**",
            "",
            "## Final-test policy",
            "",
            "The test IDs are fixed in `data/processed/split_manifest.csv`. Model selection, feature fitting, threshold selection, calibration, and augmentation must use train/validation only. The test split contains only supplied labeled examples and no synthetic data.",
            "",
            "## Constraint and limitation",
            "",
            "Source-post groups are large (the largest contains "
            + str(report["largest_group"])
            + " records), so exact 70/15/15 row counts and perfect per-class stratification are mathematically constrained. Leakage isolation takes priority over exact proportions.",
            "",
        ]
    )
    return "\n".join(lines)


def prepare_dataset(
    input_path: Path,
    interim_dir: Path,
    processed_dir: Path,
    reports_dir: Path,
    seed: int = 42,
) -> dict[str, object]:
    frame = pd.read_parquet(input_path)
    required = {
        "id",
        "text_raw",
        "source_url",
        "category",
        "sentiment",
        "priority",
    }
    missing = sorted(required - set(frame.columns))
    if missing:
        raise ValueError(f"Missing required columns: {missing}")
    if frame["id"].astype(str).duplicated().any():
        raise ValueError("Cannot split a dataset containing duplicate IDs")
    config = NormalizationConfig()
    prepared = frame.copy()
    prepared["text_normalized"] = prepared["text_raw"].fillna("").astype(str).map(
        lambda text: normalize_text(text, config)
    )
    prepared["leakage_group"] = build_leakage_groups(prepared)
    split_config = SplitConfig(seed=seed)
    prepared["split"] = grouped_multitarget_split(prepared, split_config)
    checks = leakage_check(prepared)
    if not checks["passed"]:
        raise RuntimeError(f"Leakage check failed: {checks}")
    if prepared["text_normalized"].str.strip().eq("").any():
        raise ValueError("Normalization produced an empty model input")
    interim_dir.mkdir(parents=True, exist_ok=True)
    processed_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)
    prepared.to_parquet(interim_dir / "dataset_normalized.parquet", index=False)
    manifest = prepared[["id", "leakage_group", "split"]].copy()
    manifest.to_csv(processed_dir / "split_manifest.csv", index=False, encoding="utf-8-sig")
    for split_name in ("train", "validation", "test"):
        prepared.loc[prepared["split"] == split_name].to_parquet(
            processed_dir / f"{split_name}.parquet", index=False
        )
    split_details = {}
    for name, group in prepared.groupby("split"):
        details = _distribution(group)
        details["percentage"] = round(len(group) * 100 / len(prepared), 2)
        split_details[str(name)] = details
    report: dict[str, object] = {
        "seed": seed,
        "rows": int(len(prepared)),
        "groups": int(prepared["leakage_group"].nunique()),
        "largest_group": int(prepared.groupby("leakage_group").size().max()),
        "normalization": {
            "unicode_form": "NFC",
            "replace_urls": config.replace_urls,
            "replace_emails": config.replace_emails,
            "replace_phone_numbers": config.replace_phone_numbers,
            "replace_order_ids": config.replace_order_ids,
            "preserve_punctuation_emoji_negation_case": True,
            "changed_rows": int(prepared["text_normalized"].ne(prepared["text_raw"].astype(str)).sum()),
        },
        "splits": split_details,
        "leakage_checks": checks,
        "test_policy": "locked_real_human_labeled_holdout_not_for_model_selection",
    }
    (reports_dir / "split_quality.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (reports_dir / "preprocessing_and_split.md").write_text(
        _report_markdown(report), encoding="utf-8"
    )
    return report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=Path("data/processed/dataset_version_1.parquet"))
    parser.add_argument("--interim-dir", type=Path, default=Path("data/interim"))
    parser.add_argument("--processed-dir", type=Path, default=Path("data/processed"))
    parser.add_argument("--reports-dir", type=Path, default=Path("reports"))
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    args = parse_args()
    report = prepare_dataset(
        args.input.resolve(),
        args.interim_dir.resolve(),
        args.processed_dir.resolve(),
        args.reports_dir.resolve(),
        args.seed,
    )
    LOGGER.info("Prepared %d rows into %d leakage groups", report["rows"], report["groups"])


if __name__ == "__main__":
    main()
